project:
  type: website
  output-dir: docs

website:
  title: "Data Scientist Life"
  navbar:
    left:
      - icon: houses
        href: index.qmd
        text: Home
      #- href: about.qmd
      #  text: About
      - icon: robot
        href: projects.qmd
        text: Projects
      - icon: newspaper
        href: blog.qmd
        text: Blog        
  favicon: "images/github.png"
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-link: false
    code-fold: show
    code-tools: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    grid:
      body-width: 950px
      margin-width: 200px

editor: visual

